project_id = "kapauudeaollnikedsta"

[functions.create-key]
verify_jwt = true

[functions.reset-key]
verify_jwt = true

[functions.get-key-details]
verify_jwt = true

[functions.delete-key]
verify_jwt = true

[functions.block-key]
verify_jwt = true

[functions.unblock-key]
verify_jwt = true

[functions.ban-udid]
verify_jwt = true

[functions.check-key-status]
verify_jwt = false

